[[metrics]]
= 暴露Reactor的指标

Reactor项目是一个旨在提高性能和更好地利用资源的库。但是要真正了解一个系统的性能，最好是能够监视其各种组件。

这也是为什么Reactor提供了一个内置的 https://micrometer.io[Micrometer] 集成的原因。

TIP: 如果Micrometer不在类路径上，指标将是不可操作的。

== 调度器指标

Reactor中的每个异步操作都是通过<<schedulers>>中描述的调度器抽象来完成的。这就是为什么监控你的调度器是很重要的，注意关键指标开始出现可疑的情况并作出相应反应。

要启用调度器指标，你需要使用以下方法：
====
[source,java]
----
Schedulers.enableMetrics();
----
====

WARNING: 在调度器创建时执行检测。建议尽早调用该方法。

TIP: 如果你使用的是Spring Boot，那么最好将调用放在 `SpringApplication.run(Application.class, args)` 调用之前。

一旦调度器指标被启用，并且只要它在类路径上，Reactor将使用Micrometer的支持来检测背后的大多数调度器的执行器。

关于暴露的指标，请参考 http://micrometer.io/docs/ref/jvm[Micrometer的文档]，如：

- executor_active_threads
- executor_completed_tasks_total
- executor_pool_size_threads
- executor_queued_tasks
- executor_secounds_{count, max, sum}

由于一个调度器可能有多个执行器，每个执行器指标都有一个 `reactor_scheduler_id` 标签。

TIP: Grafana + Prometheus用户可以使用 https://raw.githubusercontent.com/reactor/reactor-monitoring-demo/master/dashboards/schedulers.json[预建仪表板]，其中包含线程，已完成任务，任务队列和其它有用的指标。

== 生产者指标
有时，在响应式管道的某个阶段能够记录指标是非常有用的。

一种方法是将值手动推送到你选择的指标后端。另一种选择是使用Reactor内置的 `Flux`/`Mono` 的指标集成，并解析它们。

考虑下面的管道：
====
[source,java]
----
listenToEvents()
    .doOnNext(event -> log.info("Received {}", event))
    .delayUntil(this::processEvent)
    .retry()
    .subscribe();
----
====

为了启用这个 `Flux`（从 `listenToEvents()` 返回的） 的指标，我们需要为其命名并启用指标收集：
====
[source,java]
----
listenToEvents()
    .name("events") <1>
    .metrics() <2>
    .doOnNext(event -> log.info("Received {}", event))
    .delayUntil(this::processEvent)
    .retry()
    .subscribe();
----
<1> 在这一阶段，每个指标都将会被确定为 “事件”。
<2> `Flux#metrics` 操作符启用指标报告并使用管道中的最后一个的名称。
====

只需要加上这两个操作符，就会暴露出一大堆有用的指标!

[width="100%",options="header"]
|=======
| 指标名 | 类型 | 描述

| reactor.subscribed | 计数 | 统计订阅了多少响应式序列

| reactor.malformed.source | 计数 | 统计从异常的源（即onComplete之后的onNext）接收到的事件

| reactor.requested | 分发概括 | 统计所有订阅者对命名Flux的请求量，直到至少有一个无界数量的请求为止

| reactor.onNext.delay | 计时器 | 计量onNext信号之间的延迟

| reactor.flow.duration | 计时器 | 从订阅到序列终止或取消之间的持续时间。添加状态标签以指定什么事件导致计时器结束（`onComplete`、`onError`、`cancel`）。
|=======

想知道你的事件处理由于某些错误而重启了多少次？请阅读 `reactor.subscribed`，因为 `retry()` 操作符在发生错误时会重新订阅生产者源。

对 “每秒的事件数” 指标感兴趣？测量 `reactor.onNext.delay` 的计数的速率。

想在监听器抛出错误时得到告警？带 `status=error` 标签的 `reactor.flow.duration` 是你的朋友。

=== 常用标签

每个指标都有以下共同的标签：
[width="100%",options="header"]
|=======
| 标签名称 | 描述 | 样例

| type | 生产者类型 | "Mono"

| flow | 当前流的名称，由 `.name()` 操作符设置 | "events"
|=======

=== 自定义标签

允许用户添加自定义标签到其响应式链：
====
[source,java]
----
listenToEvents()
    .tag("source", "kafka") <1>
    .name("events")
    .metrics() <2>
    .doOnNext(event -> log.info("Received {}", event))
    .delayUntil(this::processEvent)
    .retry()
    .subscribe();
----
<1> 设置一个自定义标签“source”为“kafka”。
<2> 除了上述常见的标签外，所有报告的指标都会有 `source=kafka` 标签。

====
