[[producing]]
= 以编程方式创建序列
在这一节中，我们将通过以编程方式定义其关联的事件（`onNext`，`onError`，和 `onComplete`）来介绍 `Flux` 或 `Mono` 的创建。所有这些方法都有一个共同点，即它们暴露了一个API来触发我们称之为 *sink* 的事件。实际上有一些sink的形式，稍后我们将介绍。

[[producing.generate]]
== 同步 `generate`
`Flux` 的最简单的编程创建形式是通过具有生成器功能的 `generate` 方法。

这用于 *synchronous* 和 *一对一* 发射，这意味着该sink是一个 `SynchronousSink`，并且每次回调调用最多只能调用其 `next()` 方法一次。然后你可以另外调用 `error(Throwable)` 或 `complete()`，但这是可选的。

最有用的形式可能是一种能让你保留一个状态，你可以在你sink的使用中参考这个状态来决定下一步发出什么。然后生成器函数变成了 `BiFunction<S, SynchronousSink<T>, S>`，其中 `<S>` 是状态对象的类型。你必须为初始状态提供一个 `Supplier<S>`，你的生成器函数现在每轮都会返回一个新的状态。

例如，你可以使用 `int` 作为状态：

.基于状态 `generate` 的示例
====
[source,java]
----
Flux<String> flux = Flux.generate(
    () -> 0, // <1>
    (state, sink) -> {
      sink.next("3 x " + state + " = " + 3*state); // <2>
      if (state == 10) sink.complete(); // <3>
      return state + 1; // <4>
    });
----
<1> 我们提供初始的状态值为0。
<2> 我们用状态来选择要发出什么（3的乘法表中的一行）。
<3> 我们还可以用它来选择什么时候停止。
<4> 我们返回一个新的状态，在下一个调用中使用（除非这个序列在这个调用中终止）。
====

前面的代码生成3的乘法表，如下所示：

====
----
3 x 0 = 0
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30
----
====

你还可以使用可变的 `<S>`。例如，上面的例子可以使用一个单独的 `AtomicLong` 作为状态来重写，在每一轮对其进行修改：

.可变状态形式
====
[source,java]
----
Flux<String> flux = Flux.generate(
    AtomicLong::new, // <1>
    (state, sink) -> {
      long i = state.getAndIncrement(); // <2>
      sink.next("3 x " + i + " = " + 3*i);
      if (i == 10) sink.complete();
      return state; // <3>
    });
----
<1> 这次，我们生成一个可变的对象作为状态。
<2> 我们在这里改变状态。
<3> 我们返回 *相同* 实例作为新状态。
====

TIP: 如果你的状态对象需要清理一些资源，请使用 `generate(Supplier<S>, BiFunction, Consumer<S>)` 形式来清理最后的状态实例。

下面的例子使用来包含一个 `Consumer` 的 `generate` 方法：

====
[source, java]
----
Flux<String> flux = Flux.generate(
    AtomicLong::new,
      (state, sink) -> { // <1>
      long i = state.getAndIncrement(); // <2>
      sink.next("3 x " + i + " = " + 3*i);
      if (i == 10) sink.complete();
      return state; // <3>
    }, (state) -> System.out.println("state: " + state)); // <4>
}
----
<1> 同样，我们生成一个可变对象作为状态。
<2> 我们在这里改变状态。
<3> 我们返回 *相同* 实例作为新状态。
<4> 我们把最后一个状态值（11）视为这个 `Consumer` lambda的输出。
====

在包含数据库连接或其他资源的状态需要在进程结束时处理的情况下，`Consumer` lambda可以关闭连接或以其它方式处理任何应在进程结束时完成的任务。

[[producing.create]]
== 异步和多线程：`create`

`create` 是一种更高级的编程方式创建 `Flux` 的形式，它适合每轮多次发出，甚至来自多个线程。

它暴露了一个 `FluxSink` 及其 `next`，`error` 和 `complete` 方法。与 `generate` 相反，它没有基于状态的形式。但是，它可以在回调中触发多线程事件。

TIP: `create` 将现有的API和响应式世界桥接起来非常有用 - 例如基于监听器的异步API。

WARNING: `create` *不能使你的代码并行化你，也不能使其异步化*，即使它 *可以* 与异步API一起使用。如果在 `create` lambda中阻塞了，则会使自己陷入死锁和类似副作用中。即使使用了 `subscribeOn`，也需要警惕，即长时间阻塞的 `create` lambda（比如无限循环的调用 `sink.next(t)`）会锁住管道：这些请求永远不会执行，因为循环会耗尽应运行它们的线程。使用 `subscribeOn(Scheduler, false)` 的形式：`requestOnSeparateThread = false` 将使用 `Scheduler` 线程来进行 `create`，并且仍然可以通过在原始的线程中执行 `request` 来让数据流动。

假设你使用了基于监听器的API。它按块处理数据，并有两个事件：（1）数据块已准备就绪；（2）处理已完成（终止事件），如 `MyEventListener` 接口所示：

====
[source,java]
----
interface MyEventListener<T> {
    void onDataChunk(List<T> chunk);
    void processComplete();
}
----
====

你可以使用 `create` 将其桥接成 `Flux<T>` 中：

====
[source,java]
----
Flux<String> bridge = Flux.create(sink -> {
    myEventProcessor.register( // <4>
      new MyEventListener<String>() { // <1>

        public void onDataChunk(List<String> chunk) {
          for(String s : chunk) {
            sink.next(s); // <2>
          }
        }

        public void processComplete() {
            sink.complete(); // <3>
        }
    });
});
----
<1> 桥接到 `MyEventListener` API
<2> 块中的每个元素都会成为 `Flux` 中的一个元素。
<3> `processComplete` 事件被转换为 `onComplete`。
<4> 所有这些都是在 `myEventProcessor` 执行时异步完成的。
====

此外，由于 `create` 可以桥接异步API并管理背压，所以你可以通过声明 `OverflowStrategy` 来细化背压的行为：

 - `IGNORE` 完全忽略下游背压请求。当下游队列满时，可能会产生 `IllegalStateException`。
 - `ERROR` 当下游无法跟上时，发出 `IllegalStateException` 信号。
 - `DROP` 如果下游还没有准备好接收信号，则丢弃传入的信号。
 - `LATEST` 让下游只能获得来自上游的最新信号。
 - `BUFFER`（默认值）在下游无法跟上时，缓冲所有的信号（这将无限制的缓冲，可能会导致 `OutOfMemoryError`）。

NOTE: `Mono` 也有一个 `create` 生成器。`Mono` 创建的 `MonoSink` 不允许多次发出。它将在第一个信号之后丢弃所有信号。

== 异步单线程：`push`
`push` 介于 `generate` 和 `create` 之间，适用于处理来自单个生产者的事件。从某种意义上说，它类似于 `create`，因为它也可以是异步的，并且可以使用 `create` 所支持的任何溢出策略来管理背压。但是，**只能有一个生产线程** 可以调用 `next`，`complete` 或者 `error`。

====
[source,java]
----
Flux<String> bridge = Flux.push(sink -> {
    myEventProcessor.register(
      new SingleThreadEventListener<String>() { // <1>

        public void onDataChunk(List<String> chunk) {
          for(String s : chunk) {
            sink.next(s); // <2>
          }
        }

        public void processComplete() {
            sink.complete(); // <3>
        }

        public void processError(Throwable e) {
            sink.error(e); // <4>
        }
    });
});
----
<1> 桥接到 `SingleThreadEventListener` API。
<2> 使用单个监听器线程中的 `next` 将事件推送到 sink。
<3> 由同一监听器线程生成的 `complete` 事件。
<4> `error` 事件也是由同一监听器线程生成的。
====

=== 混合式推/拉模型
大多数响应式操作符，比如 `create`，都遵循混合的 **推/拉** 模型。我们的意思是，尽管大多数处理都是异步的（建议使用 _推_ 方法），但也有一个小的 _拉_ 组件：请求。

从源来看，消费者从源 _拉_ 数据，直到第一次请求之前，它不会发出任何东西。只要有可用的数据时，源会向消费者 _推_ 送数据，但会在其请求数量的范围内。

注意，`push()` 和 `create()` 都允许设置一个 `onRequest` 消费者，以便于管理请求量，并确保只有当有待处理的请求时，才将数据推送到sink中。

====
[source,java]
----
Flux<String> bridge = Flux.create(sink -> {
    myMessageProcessor.register(
      new MyMessageListener<String>() {

        public void onMessage(List<String> messages) {
          for(String s : messages) {
            sink.next(s); // <3>
          }
        }
    });
    sink.onRequest(n -> {
        List<String> messages = myMessageProcessor.getHistory(n); // <1>
        for(String s : message) {
           sink.next(s); // <2>
        }
    });
});
----
<1> 请求时轮询消息。
<2> 如果消息立即可用，将其推送到接收器。
<3> 稍后异步到达的其余消息也将被传递。
====

=== 在 `push()` 或 `create()` 之后清理

两个回调，`onDispose` 和 `onCancel`，在取消或终止时执行任何清理。`onDispose` 可用于 `Flux` 完成、错误或取消时执行清理。`onCancel` 可以用于在使用 `onDispose` 执行清理之前，执行任何特定于取消的操作。

====
[source,java]
----
Flux<String> bridge = Flux.create(sink -> {
    sink.onRequest(n -> channel.poll(n))
        .onCancel(() -> channel.cancel()) // <1>
        .onDispose(() -> channel.close())  // <2>
    });
----
<1> `onCancel` 首先被调用，仅用于取消信号。
<2> 完成、错误或取消信号时调用 `onDispose`。
====

== 处理
`handle` 方法有点不同：它是一个实例方法，意味着它被链接到一个现有的源（就像常见的操作符）上。它存在于 `Mono` 和 `Flux` 中。

它靠近于 `generate`，从某种意义上说，它使用 `SynchronousSink` 并只允许逐个的发出。但是，`handle` 可以用来从每个源元素中生成一个任意值，可能会跳过一些元素。这样，它可以作为 `map` 和 `filter` 的组合。handle的方法签名如下：

====
[source,java]
----
Flux<R> handle(BiConsumer<T, SynchronousSink<R>>);
----
====

让我们考虑一个例子。响应式流规范不允许序列中的值为 `null`。但是你想使用一个预先存在的方法作为map函数来执行 `map`，而该方法有时返回null怎么办？

例如，下面的方法可以安全地应用于整数源：

====
[source,java]
----
public String alphabet(int letterNumber) {
	if (letterNumber < 1 || letterNumber > 26) {
		return null;
	}
	int letterIndexAscii = 'A' + letterNumber - 1;
	return "" + (char) letterIndexAscii;
}
----
====

然后，我们可以使用 `handle` 来删除任何空值：

.`handle` 用于 "映射和消除null值" 的场景
====
[source,java]
----
Flux<String> alphabet = Flux.just(-1, 30, 13, 9, 20)
    .handle((i, sink) -> {
        String letter = alphabet(i); // <1>
        if (letter != null) // <2>
            sink.next(letter); // <3>
    });

alphabet.subscribe(System.out::println);
----
<1> 映射到字母。
<2> 如果 “map函数” 返回null....
<3> 通过不调用 `sink.next` 来过滤掉它。
====

将打印出：

====
----
M
I
T
----
====
