[[testing]]
= 测试

无论你是写了一个简单的Reactor操作符链还是自己的操作符，自动化测试都是一个不错的选择。

Reactor自带了一些专门用于测试的元素，汇总到自己的artifact：`reactor-test`。在 `reactor-core` 仓库中，你能够 https://github.com/reactor/reactor-core/tree/master/reactor-test/src[在Github] 找到该项目。

要在测试中使用它，你必须将其添加作为测试依赖。下面的例子显示了如何在Maven中怎么添加 `reactor-test` 作为依赖：

.Maven中的reactor-test, 在 `<dependencies>`
====
[source,xml]
----
<dependency>
    <groupId>io.projectreactor</groupId>
    <artifactId>reactor-test</artifactId>
    <scope>test</scope>
    <1>
</dependency>
----
<1> 如果你使用了 <<getting,BOM>>，你不需要指定 `<version>`。
====

下面的例子显示了如何在Gradle中添加 `reactor-test` 作为依赖：

.Gradle中的reactor-test, 修改 `dependencies` 块
====
[source,groovy]
----
dependencies {
   testCompile 'io.projectreactor:reactor-test'
}
----
====

`reactor-test` 的三个主要用途如下：

* 用 `StepVerifier` 逐步测试一个序列是否遵循给定的场景。
* 生产数据，以便用 `TestPublisher` 测试下游操作符（包括你自己的操作符）的行为。
* 在可以经过多个可选择的 `Publisher` 的序列(例如，一个使用 `switchIfEmpty` 的链，进行 `Publisher` 的探测，以确保它已被使用（即已订阅）) 中。

== 使用 `StepVerifier` 测试一个场景

测试Reactor序列最常见的情况是在你代码中定义了一个 `Flux` 或者 `Mono`（例如，可能是由一个方法返回的），想要测试它在订阅时的行为。 

这种情况可以很好地转化为定义一个 "`测试场景`"，可以根据事件，一步步定义你的期望。你可能会问到并回答诸如下面的问题：

* 下一个预期的事件是什么？
* 你希望 `Flux` 发射出一个特定的值？
* 或者在接下来的300ms内什么都不做？

你可以通过 `StepVerifier` API来表达这一切。

例如，你可以在你的代码库中使用下面的工具方法来装饰一个 `Flux`：

====
[source,java]
----
public <T> Flux<T> appendBoomError(Flux<T> source) {
  return source.concatWith(Mono.error(new IllegalArgumentException("boom")));
}
----
====

为了测试它，你要验证以下场景：

> 我希望这个 `Flux` 首先产生 `thing1`，然后产生 `thing2`，接着 *产生带有错误消息* 的 `boom`。订阅并 *验证* 这些期望。

在 `StepVerifier` API中，这可以转化为以下测试：

====
[source,java]
----
@Test
public void testAppendBoomError() {
  Flux<String> source = Flux.just("thing1", "thing2"); // <1>

  StepVerifier.create( // <2>
    appendBoomError(source)) // <3>
    .expectNext("thing1") // <4>
    .expectNext("thing2")
    .expectErrorMessage("boom") // <5>
    .verify(); // <6>
}
----
<1> 因为我们的方法需要一个源 `Flux`，所以定义一个简单的源来作为测试。
<2> 创建一个 `StepVerifier` 构建器，用于封装和验证 `Flux`。
<3> 传递要测试的 `Flux`（调用我们工具方法的结果）。
<4> 我们期望在订阅时产生的第一个信号是 `onNext`，值为 `thing1`。
<5> 我们期望的最后一个信号是以 `onError` 终止序列。这个异常应该包含 `boom` 信息。
<6> 重要的是通过调用 `verify()` 触发测试。
====

这个API是一个构建器。你首先创建 `StepVerifier` 并传递要测试的序列。这提供了一种方法选择，可以让你：

* 表达对下一个信号发生的期望。如果收到任何其他信号（或者信号的内容与预期不符），整个测试都会以一个有意义的 `AssertionError` 失败。例如，你可以使用 `expectNext(T...)` 和 `expectNextCount(long)`。
* 消费下一个信号。当你想要略过序列的一部分，或者想对信号的内容应用一个自定义的 `assertion`（例如，为了检测是否存在 `onNext` 事件并断言产生的列表元素个数大小为5），例如，你可以使用 `consumeNextWith(Consumer<T>)`。
* 执行诸如暂停或运行任意代码等其他操作。例如，如果你想要操纵一个特定的测试状态或上下文。为此，你可以使用 `thenAwait(Duration)` 和 `then(Runnable)`。

对于终止事件，相应的期望方法（`expectComplete()` 和 `expectError()` 及其其它的形式）会切换到一个你无法再表达期望的API中。在这最后一步，你能做的就是再 `StepVerifier` 上执行一些额外的配置，然后触发验证，通常是用 `verify()` 或其其它形式之一。

此时， `StepVerifier` 订阅了被测试的 `Flux` 或 `Mono`，并触发序列的开始，将每一个新信号与场景中的下一个步骤进行比较。只要这些符合，测试就视为成功。一旦有一个差异，将会抛出 `AssertionError` 。

IMPORTANT: 记住 `verify()` 步骤，它触发了验证。为了提供帮助，API包含了一些快捷方法，将终止期望与调用 `verify()` 结合起来： `verifyComplete()`，`verifyError()`，`verifyErrorMessage(String)` 等。

注意，如果其中一个基于lambda的期望抛出一个 `AssertionError`，则会按原样报告，测试失败。这对于自定义断言是很有用。

TIP: 默认情况下，`verify()` 方法和派生的快捷方法（`verifyThenAssertThat`，`verifyComplete()` 等）没有超时时间。它们可以无限制地阻塞。你可以使用 `StepVerifier.setDefaultTimeout(Duration)` 为这些方法全局设置一个超时时间，或者用 `verify(Duration)` 指定一个超时。

=== 更好地识别测试失败

`StepVerifier` 提供了两个选项，以更好地确定是哪个期望步骤导致测试失败：

* `as(String)`：用在大多数 `expect*` 方法之后，用于给出先前期望的描述。如果期望失败，其错误信息会包含该描述。终止期望和 `verify` 不能使用该方式进行描述。
* `StepVerifierOptions.create().scenarioName(String)`：通过使用 `StepVerifierOptions` 来创建你的 `StepVerifier`，你可以使用 `scenarioName` 方法为整个场景命名，这个名字也可用于在断言错误信息中。

注意，在两种情况下，只能保证在使用 `StepVerifier` 它们自己的方法产生的 `AssertionError` 信息中使用描述和名称（例如，手动抛出一个异常或通过 `assertNext` 中的断言库，则不会将描述或名称添加到错误消息中）。

== 操纵时间

你可以使用基于时间的操作符的 `StepVerifier` 来避免相应的测试长时间的运行。你可以通过 `StepVerifier.withVirtualTime` 构建器来实现。

它看起来像下面这个例子：

====
[source,java]
----
StepVerifier.withVirtualTime(() -> Mono.delay(Duration.ofDays(1)))
//... 这里继续期望
----
====

这个虚拟时间的功能在Reactor的 `Schedulers` 工厂中插入一个自定义的 `Scheduler`。由于这些时间操作符通常使用默认的 `Schedulers.parallel()` 调度器，所以用 `VirtualTimeScheduler` 代替它就行了。但是，一个重要的前提是，这个操作符必须在虚拟时间调度器被激活后实例化。

为了增加这种情况正确发生的几率，`StepVerifier` 不接受简单的 `Flux` 作为输入。`withVirtualTime` 需要一个 `Supplier`，在完成调度器的设置后，它会缓慢地引导你创建被测试的Flux的实例。

IMPORTANT: 请格外小心，确保在懒加载下 `Supplier<Publisher<T>>` 能被使用。否则，虚拟时间无法被保证。特别是避免在测试代码中 `Flux` 的过早实例化和并让 `Supplier` 返回该变量。相反，总是在lambda中实例化 `Flux`。

处理时间的期望方法有两种，不管有没有虚拟时间，都是有效的。

* `thenAwait(Duration)`：暂停步骤的计算（允许一些信号发生或延迟耗尽）。
* `expectNoEvent(Duration)`：也可以让序列在给定的持续时间内产生元素，但是如果在这段时间内有 _其它_ 信号产生，则测试失败。

在经典模式下，这两种方法都会暂停线程的给定时间，而在虚拟模式下，则会提前虚拟时钟。

[[tip-expectNoEvent]]
TIP: `expectNoEvent` 也将 `subscription` 视为一个事件。如果你把它作为第一步使用，通常会失败，因为会检测到订阅信号。用 `expectSubscription().expectNoEvent(duration)` 代替它。

为了快速计算我们上面的 `Mono.delay` 的行为，可以通过以下方式完成代码的编写：

====
[source,java]
----
StepVerifier.withVirtualTime(() -> Mono.delay(Duration.ofDays(1)))
    .expectSubscription() // <1>
    .expectNoEvent(Duration.ofDays(1)) // <2>
    .expectNext(0L) // <3>
    .verifyComplete(); // <4>
----
<1> 见前面的 <<tip-expectNoEvent,tip>>。
<2> 期待一整天都不会有什么事情发生。
<3> 然后期待发射数据是 `0`。
<4> 然后期待完成（并触发验证）。
====

我们可以使用上面的 `thenAwait(Duration.ofDays(1))`，但 `expectNoEvent` 能够确保什么都不会过早发生。

注意，`verify()` 返回一个 `Duration`。这是整个测试的实时持续时间。

WARNING: 虚拟时间不是银弹。所有的 `Schedulers` 都是被替换为相同的 `VirtualTimeScheduler`。在某些情况下，你可以锁定验证过程，因为在期望表达前，虚拟时钟并未开始计时，从而导致在期望等待的数据只能提前产生。在大多数情况下，你需要将虚拟时钟提前，才能发出序列。无限序列的虚拟时间也会受到限制，这可能会占用序列和检测运行所在的线程。

== 用 `StepVerifier` 执行执行后断言

在描述了你的场景中的最终期望后，你可以切换到一个补充的断言API，而不是触发 `verify()`。为此，你需要使用 `verifyThenAssertThat()`。

`verifyThenAssertThat()` 返回一个 `StepVerifier.Assertions` 对象，一旦整个场景成功地执行了，你可以使用它来断言一些状态元素（因为它同样会调用 `verify()`）。典型（即高级）的用法是捕获被某些操作符丢弃的元素并断言它们（参见<<hooks,钩子>>章节）。

== 测试 `上下文`

关于 `上下文` 的更多信息，请看<<context>>。

在 `Context` 的传播过程中，`StepVerifier` 附带一些期望：

* `expectAccessibleContext`：返回一个 `ContextExpectations` 对象，你可以使用这个对象来设置在传播 `Context` 的期望。确保调用 `then()` 能够返回到序列期望集。

* `expectNoAccessibleContext`：设置了一个期望，使其在被测试的操作符链上不能传播任何 `Context`。这最有可能发生在当测试的不是响应式的 `Publisher` 或没有任何可以传播 `Context`（例如，生成器源）的操作符

此外，你可以通过使用 `StepVerifierOptions` 来创建验证器，将特定于测试的初始 `Context` 关联到 `StepVerifier`。

下面的片段展示了这些特性：

====
[source,java]
----
StepVerifier.create(Mono.just(1).map(i -> i + 10),
				StepVerifierOptions.create().withInitialContext(Context.of("thing1", "thing2"))) // <1>
		            .expectAccessibleContext() //<2>
		            .contains("foo", "bar") // <3>
		            .then() // <4>
		            .expectNext(11)
		            .verifyComplete(); // <5>
----
<1> 通过使用 `StepVerifierOptions` 创建 `StepVerifier` 并传递一个初始化的 `Context`。
<2> 开始设置关于 `Context` 传播的期望。仅此一项就可以确保 `Context` 的传播。
<3> 特定 `Context` 期望的一个例子。它必须包含键 "thing1" 的值 "thing2"。
<4> 我们使用 `then()` 切换回对数据设置正常对期望。
<5> 让我们不要忘记对整个期望集合进行 `verify()`。
====

== 用 `TestPublisher` 手动发射

对于更高级的测试用例来说，完全掌握数据源，能够触发精心选择的信号，使之与你要测试的特定情况紧密匹配会更有用。

另一种情况是当你已经实现了自己的操作符，想要验证其在关于响应式流规范的行为，特别是其源不能够很好表现时。

对于这两种情况，`reactor-test` 提供了 `TestPublisher` 类。这是一个能让你以编程方式触发各种信号的 `Publisher<T>`：

* `next(T)` 和 `next(T, T...)` 触发1到n个 `onNext` 信号。
* `emit(T...)` 触发1到n个 `onNext` 信号并执行 `complete()`。
* `complete()` 以 `onComplete` 信号终止。
* `error(Throwable)` 以 `onError` 信号终止。

你可以通过 `create` 工厂方法获得一个表现良好的 `TestPublisher`。另外，你也可以通过使用 `createNonCompliant` 工厂方法创建一个表现不好的 `TestPublisher`。后者从 `TestPublisher.Violation` 枚举中取一个或多个值。这些值定义了生产者可以忽略规范中的哪些部分。这些枚举值包括：

* `REQUEST_OVERFLOW`：允许在请求不足的情况下进行 `next` 调用，且不会触发 `IllegalStateException`。
* `ALLOW_NULL`：允许 `null` 值进行 `next` 调用而不会触发 `NullPointerException` 异常。
* `CLEANUP_ON_TERMINATE`：允许连续多次发送终止信号。这包括 `complete()`、`error()` 和 `emit()`。
* `DEFER_CANCELLATION`：允许 `TestPublisher` 忽略取消信号并继续发送信号，就好像取消信号输掉了与所讲信号的比赛一样。

最后，`TestPublisher` 保持着订阅后的内部状态，可以通过它的各种 `assert*` 方法进行断言。

你可以使用转换方法 `flux()` 和 `mono()`，将其转换为 `Flux` 或 `Mono`。

== 用 `PublisherProbe` 检查执行路径

在构造复杂的操作符链时，你可能会遇到有几个可能的执行途经，由不同的子序列具体化的情况。

大多数时候，这些子序列会产生一个特定的 `onNext` 信号，能够通过查看最终结果来断言其已执行。

例如，考虑下面的方法，它从源构建一个操作符链，如果源为空，则使用 `switchIfEmpty` 来回退到一个特定替代的源：

====
[source,java]
----
public Flux<String> processOrFallback(Mono<String> source, Publisher<String> fallback) {
    return source
            .flatMapMany(phrase -> Flux.fromArray(phrase.split("\\s+")))
            .switchIfEmpty(fallback);
}
----
====

你可以测试使用了switchIfEmpty的哪个逻辑分支，如下所示：

====
[source,java]
----
@Test
public void testSplitPathIsUsed() {
    StepVerifier.create(processOrFallback(Mono.just("just a  phrase with    tabs!"),
            Mono.just("EMPTY_PHRASE")))
                .expectNext("just", "a", "phrase", "with", "tabs!")
                .verifyComplete();
}

@Test
public void testEmptyPathIsUsed() {
    StepVerifier.create(processOrFallback(Mono.empty(), Mono.just("EMPTY_PHRASE")))
                .expectNext("EMPTY_PHRASE")
                .verifyComplete();
}
----
====

但是，想想看一个例子，该方法产生一个 `Mono<Void>`。它等待源完成，执行一个额外的任务并完成。如果源为空，必须执行类似于 `Runnable` 的降级任务。下面的例子显示了这种情况：

====
[source,java]
----
private Mono<String> executeCommand(String command) {
    return Mono.just(command + " DONE");
}

public Mono<Void> processOrFallback(Mono<String> commandSource, Mono<Void> doWhenEmpty) {
    return commandSource
            .flatMap(command -> executeCommand(command).then()) // <1>
            .switchIfEmpty(doWhenEmpty); // <2>
}
----
<1> `then()` 忽略命令执行结果。它只关心它是否完成了。
<2> 如何区分两个都是空序列的情况？
====

为了验证你的 `processOrFallback` 方法确实执行了 `doWhenEmpty` 分支，你需要写一些样板。即你需要一个 `Mono<Void>` ：

* 捕获已经订阅的事实。
* 让你在整个过程结束 _后_ 断言该事实。

在3.1版本之前，你需要为每个你想要断言的状态手动维护一个 `AtomicBoolean`，并将相应的 `doOn*` 回调附加到你需要评估的生产者上。当需要经常使用该模式时，这可能会有很多繁琐的模版。幸运的是，3.1.0引入了 `PublisherProbe` 的替代方案。下面的例子展示了如何使用它：
====
[source,java]
----
@Test
public void testCommandEmptyPathIsUsed() {
    PublisherProbe<Void> probe = PublisherProbe.empty(); // <1>

    StepVerifier.create(processOrFallback(Mono.empty(), probe.mono())) // <2>
                .verifyComplete();

    probe.assertWasSubscribed(); //<3>
    probe.assertWasRequested(); //<4>
    probe.assertWasNotCancelled(); //<5>
}
----
<1> 创建一个转换为空序列的探针。
<2> 通过调用 `probe.mono()` 让探针代替 `Mono<Void>`。
<3> 序列完成后，探针可断言它已被使用。你能检测它是否已被订阅...
<4> ...以及实际请求的数据...
<5> ...以及是否被取消。
====

你可以通过调用 `.flux()` 替换 `.mono()`，及让探针代替 `Flux<T>`。对于你想要探针执行途经并也需要探针发射数据的情况，你可以使用 `PublisherProbe.of(Publisher)` 来封装任何 `Publisher<T>`。
